services:
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: prophius
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U prophius -d prophius -h localhost"]
      start_period: 3s
      timeout: 2s
      retries: 10